### ISSUE TITLE
Тест числа на простоту

### ISSUE THREAD

**Issue by pecourses** [SerhiiKudria/JS-Functions#1]
https://github.com/SerhiiKudria/JS-Functions/blob/8440ab86552be20b8406cf3d19313b938a9bced1/js/index.js#L11
- алгоритм невірно працює. Зокрема, він для всих парних чисел видає, що вони прості. Подивіться, наприклад, https://vscode.ru/prog-lessons/yavlyaetsya-li-chislo-prostyim-proveryaem-na-yazyike-si.html.

**Comment by SerhiiKudria** [comment]
fixed
