### ISSUE TITLE
Операція групування

### ISSUE THREAD

**Issue by pecourses** [SerhiiKudria/JS-Functions#2]
https://github.com/SerhiiKudria/JS-Functions/blob/8440ab86552be20b8406cf3d19313b938a9bced1/js/index.js#L28
- Краще не використовувати операцію групування, вона не забезпечує виконання обох умов одночасно, а повертає значення виразу після останньою коми. Подивіться в бік логічного І. 
Наприклад, `isTriangleExist(5, 10, 3)` повертає `true`, оскільки `(a > b, a > c)` повертає `5>3`, тобто `true`

**Comment by SerhiiKudria** [comment]
Навіть не знаю як тут з"явилась кома. Звичайно я використувував оператор &&

**Comment by pecourses** [comment]
👍
